// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export const adapter = new PrismaPg({
	connectionString: process.env.DATABASE_URL!
});
export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations'
	},
	datasource: {
		url: env('DATABASE_URL')
	}
});
